ARG VARIANT="jammy"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

COPY core-libs.sh /tmp/
RUN chmod +x /tmp/core-libs.sh 
ENTRYPOINT [ "/tmp/core-libs.sh" ]
CMD [ "sleep", "infinity" ]
